### ISSUE TITLE
Setting up log block with many variables fails

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-lib-python#164]
A log block can contain a maximum of 26 bytes of log data. It seems as with some configurations logging fails with less than that, which is unexpected.

## How to reproduce
Start from the basiclog.py example but change log config to:
```
	self._lg_stab.add_variable('pm.batteryLevel', 'uint8_t')
        self._lg_stab.add_variable('stateEstimateZ.quat', 'uint32_t')
        self._lg_stab.add_variable('stateEstimateZ.vx', 'int16_t')
        self._lg_stab.add_variable('stateEstimateZ.vy', 'int16_t')
        self._lg_stab.add_variable('stateEstimateZ.vz', 'int16_t')
        self._lg_stab.add_variable('stateEstimateZ.rateYaw', 'int16_t')
        self._lg_stab.add_variable('stateEstimateZ.rateRoll', 'int16_t')
        self._lg_stab.add_variable('stateEstimateZ.ratePitch', 'int16_t')
        self._lg_stab.add_variable('stateEstimate.pitch', 'float')
        self._lg_stab.add_variable('stateEstimate.roll', 'float')
```

This is 25 bytes (according to the python client) which should be fine.

## Expected behaviour

Receiving log data for the configured variables when logging is started

## Observed

```
Traceback (most recent call last):
  File "/Users/kristoffer/code/bitcraze/crazyflie-lib-python/cflib/crazyflie/__init__.py", line 399, in run
    cb.callback(pk)
  File "/Users/kristoffer/code/bitcraze/crazyflie-lib-python/cflib/crazyflie/log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "/Users/kristoffer/code/bitcraze/crazyflie-lib-python/cflib/crazyflie/log.py", line 307, in unpack_log_data
    unpackstring, log_data[data_index:data_index + size])[0]
struct.error: unpack requires a buffer of 2 bytes
```

## Notes

1. From the forum post https://forum.bitcraze.io/viewtopic.php?f=6&t=4414
1. It is possible that this is actually an issue in the crazyflie firmware

**Comment by krichardsson** [comment]
This seems to be caused by a bug in the python lib. 
When setting up a log block, there is a limit to the number of variables that fit in the block, essentially this is limited by the size of the packes sent from the CF to the client, containing log data. This limit is satisfied in this case and not a problem.

The problem in this case is the packet that is used to create the log block is too small to handle all the 10 variables. If there are too many log variables, the block must be set up using multiple messages. See https://github.com/bitcraze/crazyflie-lib-python/blob/0.1.11/cflib/crazyflie/log.py#L220

CMD_CREATE_BLOCK_V2 is used to create a block, but if all variables do not fit a second packet with the CMD_APPEND_BLOCK_V2 command must be used. This is not implemented and the maximum number of variables in a log block is currently 9 (I think).

It does not seem to be a lot of error checking for the size of packets, and this should probably be added as part of this issue as well. As far as I can see, we stuff 10 variables into the CMD_CREATE_BLOCK_V2 packet (which is too many) but it is never caught. When using radio, the tail is truncated some where on the way to the CF and 9 variables reach it. For USB it seems to hang (on MAC).
