### ISSUE TITLE
RuntimeError: Python version >= 3.7 required

### ISSUE THREAD

**Issue by AliGriv** [bitcraze/crazyflie-lib-python#195]
After forking and cloning the repository, I tried to run the command `pip3 install -e .` inside the crazyflie-lib-python folder, however, the following error showed up in the command window:

Collecting pyusb>=1.0.0b2 (from cflib===0.1.13.1)
  Using cached https://files.pythonhosted.org/packages/b5/28/b857ac783257f142932b23379d761a3d9becf6deecf5d14075ec19bdb890/pyusb-1.1.1-py3-none-any.whl
Collecting opencv-python-headless==4.5.1.48 (from cflib===0.1.13.1)
  Using cached https://files.pythonhosted.org/packages/58/bf/fe6c0714289cb408db73bd0dc6fa931e85906cb7270f7197078311be1499/opencv-python-headless-4.5.1.48.tar.gz
Collecting numpy>=1.13.3 (from opencv-python-headless==4.5.1.48->cflib===0.1.13.1)
  Using cached https://files.pythonhosted.org/packages/d2/48/f445be426ccd9b2fb64155ac6730c7212358882e589cd3717477d739d9ff/numpy-1.20.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u4wl0880/numpy/setup.py", line 30, in <module>
        raise RuntimeError("Python version >= 3.7 required.")
    RuntimeError: Python version >= 3.7 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u4wl0880/numpy/

My python version is 3.5.2 and I'm running on Ubuntu 16.04. According to the requirements that was mentioned, I thought my python version should not be an issue. I'm not really experience in this regard and I was wondering if you can help me with this issue. Thank you.

**Comment by AliGriv** [comment]
I updated my python3 to python 3.7 using the guidelines in [here](https://tech.serhatteker.com/post/2019-09/upgrade-python37-on-ubuntu18/). I also had my pip3 upgraded using `pip3 install --upgrade "pip<21"`.  That was another issue that the latest version had some problems apparently! Finally, I installed the library (cflib). However, I still don't know why that error popped up and how I could solve it without upgrading my Python.
