### ISSUE TITLE
No module named 'cflib.positioning.position_hl_commander'

### ISSUE THREAD

**Issue by ddwy** [bitcraze/crazyflie-lib-python#225]
When I click on the Crazyflie client of my desktop,the following information appears:

INFO:cfclient.gui:Disabling STL printouts
Traceback (most recent call last):
  File "./cfclient", line 5, in <module>
    main()
  File "/home/bitcraze/projects/crazyflie-clients-python/src/cfclient/gui.py", line 164, in main
    from .ui.main import MainUI
  File "/home/bitcraze/projects/crazyflie-clients-python/src/cfclient/ui/main.py", line 34, in <module>
    import cfclient.ui.tabs
  File "/home/bitcraze/projects/crazyflie-clients-python/src/cfclient/ui/tabs/__init__.py", line 34, in <module>
    from .FlightTab import FlightTab
  File "/home/bitcraze/projects/crazyflie-clients-python/src/cfclient/ui/tabs/FlightTab.py", line 45, in <module>
    from cflib.positioning.position_hl_commander import PositionHlCommander
ModuleNotFoundError: No module named 'cflib.positioning.position_hl_commander'

Hou should I solve this problem?

**Comment by krichardsson** [comment]
You probably have to upgrade your python lib.

If you are installing the client with pip you can uninstall and re-install it, that will pull in the latest version of the lib

`pip3 uninstall cfclient`
`pip3 install cfclient`

or you can upgrade the python lib with 
`pip3 install cflib --upgrade`

If you are running from source do a `git pull` for the lib
