### ISSUE TITLE
removing tuning script of examples

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-lib-python#333]
I'm getting an error from python from one of the example scripts to retrieve an parameter update. This is on Windows 11 with python 3.10 with the latest version of the cflib

```
$ python .\examples\tuning\PID_controller_tuner.py
Waiting for estimator to find position...
update info
velCtlPid.z
velCtlPid.zKp
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 3977, in __call__
    self.__callback(self.__value, *args)
  File "C:\Users\kimbe\Development\bitcraze\python\crazyflie-lib-python\examples\tuning\PID_controller_tuner.py", line 315, in change_param_unit_callback
    self.cf.param.request_param_update(
  File "c:\users\kimbe\development\bitcraze\python\crazyflie-lib-python\cflib\crazyflie\param.py", line 293, in request_param_update
    self.param_updater.request_param_update(
  File "c:\users\kimbe\development\bitcraze\python\crazyflie-lib-python\cflib\crazyflie\param.py", line 632, in request_param_update
    pk.data = struct.pack('<H', var_id)
struct.error: required argument is not an integer
```

**Comment by knmcguire** [comment]
We should remove this script from the lib  for the next release
