### ISSUE TITLE
I cannot run my basiclogSync.py

### ISSUE THREAD

**Issue by jaycariaga** [bitcraze/crazyflie-lib-python#84]
I downloaded pyCharm to run the files for my crazyflie. It worked the first couple times, but now it gives me this error message saying it cannot find "commander.py" even though it is inside that directory. And from what I remember, I'm sure cflib was installed as a package too...
_______________________________________________________________________________________________________________
ERROR MESSAGE:

C:\Users\jaymc\AppData\Local\Temp\basiclogSync.py\venv\Scripts\python.exe D:/Programs/Git/crazyflie-lib-python/examples/basiclogSync.py
Traceback (most recent call last):
  File "D:/Programs/Git/crazyflie-lib-python/examples/basiclogSync.py", line 35, in <module>
    import cflib.crtp
  File "C:\Users\jaymc\AppData\Local\Temp\basiclogSync.py\venv\lib\site-packages\cflib\crtp\__init__.py", line 30, in <module>
    from .debugdriver import DebugDriver
  File "C:\Users\jaymc\AppData\Local\Temp\basiclogSync.py\venv\lib\site-packages\cflib\crtp\debugdriver.py", line 52, in <module>
    from cflib.crazyflie.log import LogTocElement
  File "C:\Users\jaymc\AppData\Local\Temp\basiclogSync.py\venv\lib\site-packages\cflib\crazyflie\__init__.py", line 44, in <module>
    from .commander import Commander
ModuleNotFoundError: No module named 'cflib.crazyflie.commander'

**Comment by jaycariaga** [comment]
oh nevermind. I placed the content root file at the crazyflie-lib-python and mostly everything works now.
